icons_format = "{icon}"

[theme]
theme = "solarized-dark"

[icons]
icons = "awesome4"

[[block]]
block = "net"
format = " $icon "

#[[block]]
#block = "cpu"
#info_cpu = 20
#warning_cpu = 50
#critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
interval = 30

[[block]]
block = "battery"
interval = 30
format = " $icon $percentage "

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout"
[block.mappings]
"English (US)" = "en"
"Russian (N/A)" = "ru"

[[block]]
block = "time"
interval = 30
format = " $timestamp.datetime(f:'%a %d/%m %R') "
